/** Especialidades médicas frecuentes en Venezuela (orden alfabético). */
export const ESPECIALIDADES_MEDICAS_VE: string[] = [
  "Alergología",
  "Anestesiología",
  "Angiología y cirugía vascular",
  "Cardiología",
  "Cirugía cardiovascular",
  "Cirugía general",
  "Cirugía maxilofacial",
  "Cirugía pediátrica",
  "Cirugía plástica",
  "Cirugía de tórax",
  "Dermatología",
  "Endocrinología",
  "Gastroenterología",
  "Geriatría",
  "Ginecología y obstetricia",
  "Hematología",
  "Infectología",
  "Medicina crítica / UCI",
  "Medicina del deporte",
  "Medicina del trabajo",
  "Medicina familiar",
  "Medicina física y rehabilitación",
  "Medicina interna",
  "Nefrología",
  "Neumología",
  "Neurocirugía",
  "Neurología",
  "Nutrición clínica",
  "Oftalmología",
  "Oncología médica",
  "Otorrinolaringología",
  "Pediatría",
  "Psiquiatría",
  "Radiología / Imagenología",
  "Reumatología",
  "Traumatología y ortopedia",
  "Urología",
  "Otra",
];
