import "./home";
import "./registro";
import "./patients";
import "./documents";
import "./drafts";
import "./redactar";
import "./plantillas/hub";
import "./plantillas/physical-exam";
import "./plantillas/templates";
