package com.ceoclinicos.clinicosdoc.ui.screens

import android.widget.Toast
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.selection.selectable
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material.icons.filled.Save
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.RadioButton
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.semantics.Role
import androidx.compose.ui.unit.dp
import com.ceoclinicos.clinicosdoc.data.DoctorStorage
import com.ceoclinicos.clinicosdoc.data.DocumentStorage
import com.ceoclinicos.clinicosdoc.data.HeaderStorage
import com.ceoclinicos.clinicosdoc.data.PatientStorage
import com.ceoclinicos.clinicosdoc.data.TemplateStorage
import com.ceoclinicos.clinicosdoc.model.ClinicalDocument
import com.ceoclinicos.clinicosdoc.model.DocumentType
import com.ceoclinicos.clinicosdoc.model.OrdenesFromCasePending
import com.ceoclinicos.clinicosdoc.model.OrdenesMedicasDefaults
import com.ceoclinicos.clinicosdoc.model.PatientMembrete
import com.ceoclinicos.clinicosdoc.service.DocumentAiService
import com.ceoclinicos.clinicosdoc.ui.components.AppScaffold
import com.ceoclinicos.clinicosdoc.ui.components.DocumentPdfActions
import com.ceoclinicos.clinicosdoc.ui.components.EditableDocumentContent
import com.ceoclinicos.clinicosdoc.ui.components.PremiumPrimaryButton
import com.ceoclinicos.clinicosdoc.ui.theme.Teal
import com.ceoclinicos.clinicosdoc.ui.theme.TextSecondary
import kotlinx.coroutines.launch
import java.time.Instant
import java.util.UUID

@Composable
fun GenerarOrdenesFromCaseScreen(
    onBack: () -> Unit,
    onSaved: (docId: String) -> Unit,
) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    val pending = remember { OrdenesFromCasePending.take() }

    if (pending == null) {
        LaunchedEffect(Unit) { onBack() }
        return
    }

    val patient = remember(pending.patientId) {
        PatientStorage.loadAll(context).firstOrNull { it.id == pending.patientId }
    }
    val doctor = remember { DoctorStorage.loadProfile(context) }
    val header = remember(pending.headerId) {
        pending.headerId?.let { id -> HeaderStorage.loadAll(context).firstOrNull { it.id == id } }
            ?: HeaderStorage.loadAll(context).firstOrNull { it.isDefault }
            ?: HeaderStorage.loadAll(context).firstOrNull()
    }
    val template = remember {
        TemplateStorage.forType(context, DocumentType.ORDENES_MEDICAS)
            .firstOrNull { it.isDefault }
            ?: TemplateStorage.forType(context, DocumentType.ORDENES_MEDICAS).firstOrNull()
    }

    var caseText by remember { mutableStateOf(pending.caseContent) }
    var notes by remember { mutableStateOf("") }
    var modo by remember { mutableStateOf(OrdenesMedicasDefaults.Modo.ORDENES) }
    var generating by remember { mutableStateOf(false) }
    var generated by remember { mutableStateOf<String?>(null) }
    var saving by remember { mutableStateOf(false) }

    AppScaffold(
        title = "Generar órdenes",
        onBack = onBack,
    ) { padding ->
        if (patient == null || doctor == null) {
            Column(
                Modifier.fillMaxSize().padding(padding).padding(24.dp),
                horizontalAlignment = Alignment.CenterHorizontally,
            ) {
                Text("No se encontró el paciente o el perfil del médico.", color = TextSecondary)
            }
            return@AppScaffold
        }

        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .verticalScroll(rememberScrollState())
                .padding(24.dp),
        ) {
            Text(
                "${patient.nombre} · C.I. ${patient.cedula}",
                style = MaterialTheme.typography.titleMedium,
            )
            if (pending.sourceTypeLabel.isNotBlank()) {
                Text(
                    "Desde: ${pending.sourceTypeLabel}",
                    style = MaterialTheme.typography.bodySmall,
                    color = TextSecondary,
                )
            }

            if (generated == null) {
                Spacer(Modifier = Modifier.height(16.dp))
                Text("Caso clínico (editable)", style = MaterialTheme.typography.titleSmall)
                Text(
                    "Revisa o ajusta el texto antes de generar.",
                    style = MaterialTheme.typography.bodySmall,
                    color = TextSecondary,
                )
                Spacer(Modifier = Modifier.height(8.dp))
                OutlinedTextField(
                    value = caseText,
                    onValueChange = { caseText = it },
                    modifier = Modifier.fillMaxWidth().height(220.dp),
                    maxLines = 20,
                )

                Spacer(modifier = Modifier.height(16.dp))
                Text("Tipo de hoja", style = MaterialTheme.typography.titleSmall)
                OrdenesMedicasDefaults.Modo.entries.forEach { option ->
                    Row(
                        modifier = Modifier
                            .fillMaxWidth()
                            .selectable(
                                selected = modo == option,
                                onClick = { modo = option },
                                role = Role.RadioButton,
                            )
                            .padding(vertical = 4.dp),
                        verticalAlignment = Alignment.CenterVertically,
                    ) {
                        RadioButton(selected = modo == option, onClick = { modo = option })
                        Text(option.label, modifier = Modifier.padding(start = 8.dp))
                    }
                }

                Spacer(modifier = Modifier.height(12.dp))
                Text("Notas / dictado adicional (opcional)", style = MaterialTheme.typography.titleSmall)
                OutlinedTextField(
                    value = notes,
                    onValueChange = { notes = it },
                    modifier = Modifier.fillMaxWidth().height(100.dp),
                    placeholder = { Text("Ej. agregar ceftriaxona, oxígeno 2 L…") },
                    maxLines = 6,
                )

                Spacer(modifier = Modifier.height(20.dp))
                PremiumPrimaryButton(
                    label = if (generating) "Generando…" else "Generar órdenes",
                    icon = Icons.Default.AutoAwesome,
                    loading = generating,
                    modifier = Modifier.fillMaxWidth(),
                    onClick = {
                        if (caseText.isBlank()) {
                            Toast.makeText(context, "El caso clínico está vacío", Toast.LENGTH_SHORT).show()
                            return@PremiumPrimaryButton
                        }
                        generating = true
                        scope.launch {
                            try {
                                generated = DocumentAiService.generateOrdenesFromCase(
                                    context = context,
                                    patient = patient,
                                    doctor = doctor,
                                    caseContent = caseText.trim(),
                                    notes = notes.trim(),
                                    modo = modo,
                                    header = header,
                                )
                            } catch (e: Exception) {
                                Toast.makeText(
                                    context,
                                    e.message ?: "Error al generar",
                                    Toast.LENGTH_LONG,
                                ).show()
                            } finally {
                                generating = false
                            }
                        }
                    },
                )
            } else {
                Spacer(Modifier = Modifier.height(12.dp))
                Text(modo.label, style = MaterialTheme.typography.labelLarge, color = Teal)
                Spacer(Modifier = Modifier.height(8.dp))
                EditableDocumentContent(
                    content = generated.orEmpty(),
                    onContentChange = { generated = it },
                )
                Spacer(modifier = Modifier.height(12.dp))
                DocumentPdfActions(
                    document = ClinicalDocument(
                        id = "preview-ordenes",
                        patientId = patient.id,
                        patientNombre = patient.nombre,
                        patientCedula = patient.cedula,
                        type = DocumentType.ORDENES_MEDICAS,
                        content = generated.orEmpty(),
                        rawDictation = notes.trim(),
                        createdAt = Instant.now(),
                        templateId = template?.id,
                        templateName = template?.name,
                        headerId = header?.id,
                        headerSnapshot = header,
                        membrete = PatientMembrete.fromPatient(patient),
                        sourceDocumentId = pending.sourceDocumentId,
                    ),
                )
                Spacer(modifier = Modifier.height(16.dp))
                PremiumPrimaryButton(
                    label = "Guardar documento",
                    icon = Icons.Default.Save,
                    loading = saving,
                    modifier = Modifier.fillMaxWidth(),
                    onClick = {
                        val content = generated ?: return@PremiumPrimaryButton
                        saving = true
                        scope.launch {
                            val id = UUID.randomUUID().toString()
                            DocumentStorage.add(
                                context,
                                ClinicalDocument(
                                    id = id,
                                    patientId = patient.id,
                                    patientNombre = patient.nombre,
                                    patientCedula = patient.cedula,
                                    type = DocumentType.ORDENES_MEDICAS,
                                    content = content,
                                    rawDictation = notes.trim().ifBlank { caseText.take(500) },
                                    createdAt = Instant.now(),
                                    templateId = template?.id,
                                    templateName = template?.name,
                                    headerId = header?.id,
                                    headerSnapshot = header,
                                    membrete = PatientMembrete.fromPatient(patient),
                                    sourceDocumentId = pending.sourceDocumentId,
                                ),
                            )
                            saving = false
                            Toast.makeText(context, "Órdenes guardadas", Toast.LENGTH_SHORT).show()
                            onSaved(id)
                        }
                    },
                )
            }
        }
    }
}
